_wandb:
    value:
        cli_version: 0.19.4
        m:
            - "1": trainer/global_step
              "6":
                - 3
              "7": []
        python_version: 3.8.10
        t:
            "1":
                - 1
                - 5
                - 9
                - 37
                - 38
                - 41
                - 49
                - 51
                - 53
                - 55
                - 60
                - 63
            "2":
                - 1
                - 5
                - 9
                - 37
                - 38
                - 41
                - 49
                - 51
                - 53
                - 55
                - 60
                - 63
            "3":
                - 7
                - 13
                - 23
                - 55
                - 66
            "4": 3.8.10
            "5": 0.19.4
            "8":
                - 5
            "12": 0.19.4
            "13": linux-x86_64
